# HW Assignment 2 : Numpy and Scipy basic functionality

### Python with the help of popular libraries like numpy and scipy becomes a powerful environment for scientific computing.

## NumPy library : Array

### 1.Creating array using existing data : array()

In [32]:
#The central feature of NumPy is the array object class. 
#Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int.
#Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists. 
#An array can be created from a list: 

import numpy as np
a = np.array([1, 2.3, 4, 5.6], float) 
a

#syntax: array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
#Here, the function array takes two arguments:
#the list to be converted into the array and the type of each member of the list.

array([ 1. ,  2.3,  4. ,  5.6])

In [17]:
a = np.array(9)

#Array in Numpy can be zero dimentsional, one dimensional or multidimensional

#(1.1) Zero dimensional array:
np.ndim(a)

#Scalars are zero dimensional. 
#In the above example, we created the scalar 9.
#The output shows dimension of our array using the ndim() method.

0

In [18]:
#(1.2) One dimensional array (vectors) :
#Numpy arrays are containers of items of the same type

a = np.array([1, 2.3, 4, 5.6], float)    
#This is an example of 1 dimensional array with all elements having float data type.

type(a) 
 
#The function type() here provides the object type of 'a' as ndarray.
#ndarray stands for 'N dimentional array'.
#An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. 
#The number of dimensions and items in an array is defined by its shape , which is a tuple of N positive integers that specify the sizes of each dimension.

numpy.ndarray

In [19]:
#Upcasting of array.

a = np.array([1, 2.3, 4, 5])    
a

#Array stores all the elements with the same type. Since one element 2.3 was float, all other elements were upcasted here.
#The output shows that array a has all elements stored as float.

array([ 1. ,  2.3,  4. ,  5. ])

In [25]:
#(1.3) Multidimensional array:
#Array of Numpy are of arbitary dimension

a = np.array(np.mat('1 2; 3 4'))

#The above is example of a 2 dimensional array.
#The method mat() interpret the input as a matrix
#syntax : mat(data, dtype=None)[source]

a

array([[1, 2],
       [3, 4]])

In [28]:
#Another example of multidimensional array.  Unlike lists, different axes are accessed using commas inside bracket notation.  
#Here is an example with a two-dimensional array (e.g., a matrix):

a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

### 2.Creating array with values specified using arange()

In [29]:
#syntax : arange([start, ]stop, [step, ]dtype=None)
#Values are generated within the half-open interval [start, stop)
#It creates array using Numerical range function 'arange'

a = np.arange(3,7) 
a

array([3, 4, 5, 6])

In [6]:
#Accessing a array is similar to accessing a list.

a[3] 

#Here, the element of index 3 is returned.

6

### Slicing Python array:

In [27]:
#1. By giving the start and end index:

a = np.array([1, 2.3, 4, 5.6], float) 
a[1:3] 

#Here, as seen the elements between index 1 and 3 have been returned.

array([ 2.3,  4. ])

In [28]:
#2. By giving the end index:

a = np.array([1, 2.3, 4, 5.6], float) 
a[:3] 

#Here, as seen the elements between index 0 and 2 have been returned.

array([ 1. ,  2.3,  4. ])

In [30]:
#3. By giving the start , end and the slicing increment:

a = np.array([1, 2.3, 4, 5.6], float) 
a[0:3:2] 

#Here, as seen the elements between index 0 and 3 have been returned with an interval of 2 in them.
#Thus,1.0 and 4.0 were returned as they have index 1 and 3 with interval of 2 in between.

array([ 1.,  4.])

In [31]:
#Assigning new value to array elements.

a[0] = 5.
a[0]

5.0

In [32]:
a

#As seen the array a now has 0th element as 5.0

array([ 5. ,  2.3,  4. ,  5.6])

In [35]:
#Array slicing in multidimensional array:

a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]], float)
a[1,:] 

# Use of a single ":" in a dimension indicates the use of everything along that dimension

array([ 4.,  5.,  6.])

In [36]:
a[:,1]

#[:] with no arguments is the same as [:] for lists - it can be read 'all indices along this axis'. 
#So, to get the second column along the second dimension:

array([ 2.,  5.,  8.])

In [37]:
a[-1:,-2:]

#This output will return the values of 3rd row (-1) and last 2 columns (-2)

array([[ 8.,  9.]])

In [38]:
#the optional third argument, meaning the ``step size'', also called stride or increment.
#Its default value is 1, meaning return every element in the specified range. 

a[::2]

#Thus, in this case when no rows and column were selected and increment passed was 2, the 1st and 3rd rows were returned.

array([[ 1.,  2.,  3.],
       [ 7.,  8.,  9.]])

### The shape property of an array

In [44]:
# It returns a tuple of integers with the size of each array dimension: 
#These numbers denote the lengths of the corresponding array dimension.
#The shape of an array tells us also something about the order in which the indices are processed, 
# i.e. first rows, then columns and after that the further dimensions.

a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]], float)
a.shape

#Here, the array has 3 rows and 3 columns and thus output is 3,3

(3, 3)

In [46]:
#Alternate property of shape() is it can be used to change the shape of an array. 

a.shape = (1, 9)
print(a)

#As seen here the array a has now become of dimension 1,9 from 3,3

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]]


In [47]:
#The shape of a scalar is an empty tuple.

a = np.array(11)
print(np.shape(a))

()


In [51]:
#Arrays can also be reshaped using tuples that specify new dimensions.

a = np.array([1, 2, 3, 4, 5, 6,7, 8, 9], float)
a = a.reshape((3,3))
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

### The dtype in numpy

In [53]:
a = np.array([1, 2, 3, 4, 5, 6,7, 8, 9], float) 
a.dtype

#The dtype property tells you what type of values are stored by the array
#A numpy array is homogeneous, and contains elements described by a dtype object. 

dtype('float64')

### The len() function

In [54]:
#When used with an array, the len function returns the length of the first axis

a = np.array([[1, 2, 3], [4, 5, 6]], float)
len(a)  

2

### The 'in'  statement

In [56]:
#It can be used to test if values are present in an array: 

a = np.array([[1, 2, 3], [4, 5, 6]], float)
4 in a

#Since 4 is an element of array a , the output returned is True else it would have returned False.

True

### Indexing

In [58]:
#Single indexing is the way, you will most probably expect it:

a = np.array([1, 1, 2, 3, 5, 8, 13, 21])

a[5]

8

In [59]:
#Indexing multidimensional arrays:

a = np.array([ [1.2, 2.3, 3.4], 
               [4.5, 5.6, 6.7],
               [7.8, 8.9, 9.0]])
print(a[1][0])

#Here, we accessed the element in the second row, i.e. the row with the index 1, and the first column (index 0)

4.5


In [64]:
#The alternative way of accessing the elements is by seperating by commas.

a = np.array([ [1.2, 2.3, 3.4], 
               [4.5, 5.6, 6.7],
               [7.8, 8.9, 9.0]])

print(a[1,2])

6.7


### Arrays created by 1s and 0s

In [66]:
a = np.ones((2,3))
print(a)

#By default it will be filled with Ones of type float.


[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [68]:
#If you need integer Ones, you have to set the optional parameter dtype to int

a = np.ones((2,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [69]:
#The method ones() is valid for the method zeros() analogously.

a = np.zeros((2,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [71]:
#One way to create an array of 1s and 0s if it has to have the same shape as another existing array 'a'

a = np.array([1, 1, 2, 3, 5, 8, 13, 21])
b = np.ones_like(a)
b

array([1, 1, 1, 1, 1, 1, 1, 1])

In [72]:
#Similarly the array to create another array with zeros is as follows:

a = np.array([1, 1, 2, 3, 5, 8, 13, 21])
b = np.zeros_like(a)
b

array([0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
#To create an identity matrix of a given size, 
a = np.identity(4, dtype=float) 
a

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [82]:
#The eye function returns matrices with ones along the kth diagonal
a = np.eye(4, k=1, dtype=float)
a

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

### Copying arrays

In [79]:
#Return an array copy of the given object 'obj'.
#syntax : copy(obj, order='K')

a = np.array([1, 1, 2, 3, 5, 8, 13, 21])
c = a.copy()

c

array([ 1,  1,  2,  3,  5,  8, 13, 21])

In [80]:
a = np.array([1, 1, 2, 3, 5, 8, 13, 21])
b = a
b

#The direct association method also creates a copy of the array

array([ 1,  1,  2,  3,  5,  8, 13, 21])

### Array Mathematics

In [83]:
#The arrays should be the same size during addition, subtraction, etc.: 

#Addition
a = np.array([1,2,3], float)
b = np.array([5,2,6], float) 
a+b

array([ 6.,  4.,  9.])

In [84]:
#Subtraction
a = np.array([1,2,3], float)
b = np.array([5,2,6], float) 
b-a

array([ 4.,  0.,  3.])

In [86]:
#Multiplication
a = np.array([1,2,3], float)
b = np.array([5,2,6], float) 
a * b

array([  5.,   4.,  18.])

In [87]:
#Division
a = np.array([1,2,3], float)
b = np.array([5,2,6], float) 
b/a

array([ 5.,  1.,  2.])

In [88]:
#Raised to the Power
a = np.array([1,2,3], float)
b = np.array([5,2,6], float) 
b**a

array([   5.,    4.,  216.])

In [89]:
#% Operator
a = np.array([1,2,3], float)
b = np.array([5,2,6], float) 
a%b

array([ 1.,  0.,  3.])

In [90]:
#sqrt function
a = np.array([1, 4, 9], float) 
np.sqrt(a)

array([ 1.,  2.,  3.])

### Array Iteration

In [100]:
#Iterate over arrays in a manner similar to that of lists

a = np.array([1, 2,3], int) 
for x in a:
    print (x)

1
2
3


In [99]:
#For multidimensional arrays, iteration proceeds over the first axis such that each loop returns a subsection of the array

a = np.array([[1, 2], [3, 4], [5, 6]], int) 
for (x,y) in a:
    print (x*y)

2
12
30


### Basic array operation

In [101]:
#1. The items in an array can be summed:

a = np.array([2, 4, 3], float) 

a.sum()

9.0

In [102]:
#2. The items in a array can be multiplied:

a = np.array([2, 4, 3], float) 

a.prod()

24.0

In [103]:
# 3.To find mean of an array

a = np.array([2, 4, 3], float) 

a.mean()

3.0

In [104]:
# 4. To find variance of an array

a = np.array([2, 4, 3], float) 

a.var()

0.66666666666666663

In [105]:
# 5. To find standard deviation

a = np.array([2, 4, 3], float) 

a.std()

0.81649658092772603

In [106]:
# 6. To find min of the array

a = np.array([2, 4, 3], float) 

a.min()

2.0

In [107]:
# 7. To find min of the array

a = np.array([2, 4, 3], float) 

a.max()

4.0

In [108]:
# 8.The argmin function return the array indices of the minimum value

a = np.array([2, 4, 3], float) 

a.argmin()

0

In [110]:
# 9. The argmax function return the array indices of the minimum value

a = np.array([2, 4, 3], float) 

a.argmax()

1

In [113]:
# 10. To find Unique elements from an array: 

a = np.array([2, 4, 3,4,4,5,3], float) 

np.unique(a)

array([ 2.,  3.,  4.,  5.])

### Comparison operators and value testing 

In [118]:
#Greater than comparison

a = np.array([1, 4, 0], float) 
b = np.array([0, 4, 2], float)

a>b

#This function compares each element index wise of a array with the other array of equal length and type .
#The function returns True if the ith element in a is greater than b, else it returns False

array([ True, False, False], dtype=bool)

In [119]:
#Equal to comparison

a = np.array([1, 4, 0], float) 
b = np.array([0, 4, 2], float)

a==b

#The function returns True if the ith element in a is equal to b, else it returns False

array([False,  True, False], dtype=bool)

In [120]:
#Less than equal to comparison

a = np.array([1, 4, 0], float) 
b = np.array([0, 4, 2], float)

a<=b

#The function returns True if the ith element in a is less than or equal to b, else it returns False

array([False,  True,  True], dtype=bool)

In [141]:
#Arrays can be compared to single values using broadcasting: 
a = np.array([1, 4, 0], float)
a > 2 

#This function returns True if the ith element in a is greater than b, else it returns False

array([False,  True, False], dtype=bool)

### Arithmatic Operations

In [125]:
#Addition

a = np.arange(4, dtype = np.float_).reshape(2,2) 
b = np.array([3,3]) 

np.add(a,b) 

array([[ 3.,  4.],
       [ 5.,  6.]])

In [126]:
#Subtraction

a = np.arange(4, dtype = np.float_).reshape(2,2) 
b = np.array([3,3]) 

np.subtract(a,b) 

array([[-3., -2.],
       [-1.,  0.]])

In [129]:
#Multiplication

a = np.arange(4, dtype = np.float_).reshape(2,2) 
b = np.array([3,3]) 

np.multiply(a,b) 

array([[ 0.,  3.],
       [ 6.,  9.]])

In [128]:
#Division

a = np.arange(4, dtype = np.float_).reshape(2,2) 
b = np.array([3,3]) 

np.divide(a,b)

array([[ 0.        ,  0.33333333],
       [ 0.66666667,  1.        ]])

### String Functions


In [132]:
#1. add()
#This function provides string concatenation

np.char.add(['my'],[' example']) 

array(['my example'],
      dtype='<U10')

In [133]:
#2. upper()
#This function returns upper case of the string

np.char.upper(['my','example'])

array(['MY', 'EXAMPLE'],
      dtype='<U7')

In [134]:
#3. lower()
#This function returns lower case of the string

np.char.lower(['MY', 'EXAMPLE'])

array(['my', 'example'],
      dtype='<U7')

In [135]:
#4. capitalize()
#This function returns string after capitalizing first character

np.char.capitalize('my example')

array('My example',
      dtype='<U10')

In [136]:
#5. join()
#This function returns string after joining each character with the seperator

np.char.join(':','dmy') 

array('d:m:y',
      dtype='<U5')

In [137]:
#6. replace()
#This function returns the first string after replacing the second string with the thrid parameter passed.

np.char.replace ('This was my first example', 'was', 'is')

array('This is my first example',
      dtype='<U24')

In [138]:
#7. strip
#This function returns string after stripping the mentioned charater from the ends

np.char.strip('my example','m') 

array('y example',
      dtype='<U10')

In [140]:
#8. split()
#This function returns a list of words in the input string.

np.char.split ('This is my example') 

array(['This', 'is', 'my', 'example'], dtype=object)